server:
  port: 1150
spring:
  application:
    name: zuul-gateway
  profiles:
    active: dev
    include: "base"
zuul:
  # 禁止Zuul自动创建路由规则（原因：不想对外开放的服务也被外部访问到）
  # 路由规则：默认情况下，Eureka上的服务都会被Zuul创建默认的映射关系来进行路由
  ignored-services: '*'  # 过滤全部服务“'*'”; 指定服务“服务名”
  routes:
    # 此方式用于独立的域名访问
#    api-url:
#      path: /api-a/**
#      url: http://localhost:9001
    # 此方式用于服务访问，与eureka结合
    feign-context:
      path: /feign-context/**
      serviceId: feign-context
