server:
  port: 1000

spring:
  application:
    # 应用名称
    name: eureka-server
  profiles:
    include: "base"
eureka:
  # 当前微服务实例信息
  instance:
    # eureka 服务名 / 主机名,  作用域：通信
    hostname: study-springCloud-eureka
    # 访问路径是否可以显示IP地址
    prefer-ip-address: true
    # 实例名：IP:Port
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  # 微服务作为服务端时的配置信息
  server:
    # 是否开启自我保护，true:不会剔除已注册的服务; false:根据心跳管理服务
    enable-self-preservation: false
    # 服务检测失效时间间隔，单位：毫秒
    eviction-interval-timer-in-ms: 1000
    #
    use-read-only-response-cache: false
  # 微服务作为客户端时的配置信息
  client:
    # 集群配置（配置eureka注册中心的信息，多个以“逗号”分隔）,如果不需要集群，则把配置改为"false"

    # 注册中心是否注册自己
    register-with-eureka: true   # 实现集群
    # 注册中心是否主动去发现服务
    fetch-registry: true         # 实现集群
    # 设置服务注册中心的URL
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://localhost:1009/eureka
