server:
  port: 1000

spring:
  application:
    # 应用名称
    name: eureka-server
eureka:
  instance:
    hostname: study-springCloud-eureka
  server:
    # 是否开启自我保护，true:不会提出已注册的服务; false:根据心跳管理服务
    enable-self-preservation: false
    # 服务心中时间，单位：毫秒
    eviction-interval-timer-in-ms: 5000
    #
    use-read-only-response-cache: false

  client:
    # 注册中心是否注册自己
    register-with-eureka: false
    # 注册中心是否主动去发现服务
    fetch-registry: false
    # 设置服务注册中心的URL
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka


