server:
  port: 1009
eureka:
  # 微服务作为客户端时的配置信息
  client:
    # 集群配置（配置eureka注册中心的信息，多个以“逗号”分隔）,如果不需要集群，则把配置改为"false"

    # 设置服务注册中心的URL
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://localhost:1000/eureka
