server:
  port: 1010
spring:
  application:
    name: config-server
  profiles:
    include: "base"
  cloud:
    config:
      server:
        git:
          # 配置Git仓库的地址
          uri: http://git.ccuol.com/wenjie/springcloud-config.git
          # 配置仓库路径下的相对搜索位置，可以配置多个;在哪些文件下搜索
          search-paths: respo
          username: zqkh-dev
          password: 12345678