server:
  port: 1131
spring:
  application:
    name: feign-feign
  profiles:
    active: dev
    include: "base"

# 断路器配置
feign:
  hystrix:
    enabled: true
  compression:
    #请求和响应GZIP压缩支持
    request:
      enabled: true
      #支持压缩的mime types
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

## 断路器配置
#hystrix:
#  metrics:
#    enabled: true
#    # 刷新间隔
#    polling-interval-ms: 2000
